<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BikramKesharis-Mac-mini.local" failures="1" tests="7" name="com.akhilsystem_release.test.emr.DoctorAssign" time="64.729" errors="0" timestamp="2024-07-03T10:27:27 IST" skipped="0">
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="openAppointment" time="8.877"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="fstDoctorAppointment" time="15.754"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="closeAppointment" time="3.078"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="fstDoctorLogin" time="20.267"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="assignToDoctor" time="3.127"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="assignedDocLogin" time="10.659"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="verifySndDoctorData" time="2.967">
    <failure message="expected [376569] but found [971316]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [376569] but found [971316]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.akhilsystem_release.test.emr.DoctorAssign.verifySndDoctorData(DoctorAssign.java:142)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.akhilsystem_release.test.emr.TestRunner.main(TestRunner.java:49)
]]>
    </failure>
  </testcase> <!-- verifySndDoctorData -->
  <system-out/>
</testsuite> <!-- com.akhilsystem_release.test.emr.DoctorAssign -->
