<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BikramKarisMini" failures="2" tests="7" name="com.akhilsystem_release.test.emr.DoctorAssign" time="65.096" errors="0" timestamp="2024-07-01T17:17:54 IST" skipped="0">
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="openAppointment" time="9.378"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="fstDoctorAppointment" time="15.554"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="closeAppointment" time="3.587"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="fstDoctorLogin" time="20.521"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="assignToDoctor" time="1.131">
    <failure message="expected [Assigned successfully] but found [Updated Successfully]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Assigned successfully] but found [Updated Successfully]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.akhilsystem_release.test.emr.DoctorAssign.assignToDoctor(DoctorAssign.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- assignToDoctor -->
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="assignedDocLogin" time="10.647"/>
  <system-out/>
  <testcase classname="com.akhilsystem_release.test.emr.DoctorAssign" name="verifySndDoctorData" time="4.278">
    <failure message="expected [870107] but found [241250]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [870107] but found [241250]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.akhilsystem_release.test.emr.DoctorAssign.verifySndDoctorData(DoctorAssign.java:146)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- verifySndDoctorData -->
  <system-out/>
</testsuite> <!-- com.akhilsystem_release.test.emr.DoctorAssign -->
